### ISSUE TITLE
Warning: Unhandled usermessage 'glib_channels_open'

### ISSUE THREAD

**Issue by markusmarkusz** [notcake/glib#4]
I'm sure you've heard of this message/error.
The cause is also simple: The usermessage isn't registered. (`umsg.PoolString("glib_channels_open")` isn't executed anywhere)
I just don't know the exact origin of this problem. Where should the usermessage be registered?
It would be nice, if you fix this. Thanks.

**Comment by notcake** [comment]
Half of this codebase is delay-loaded. The warning means that the usermessage was received before load completed.

As it stands, this codebase is a steaming pile of trash in need of restructuring. It's unlikely this will ever be fixed.
